import { z } from 'zod';

/**
 * The skill manifest — the compact catalog index.
 *
 * The reasoning CLI's prompt only ever carries this index (id, display name,
 * one-line description), never skill bodies speculatively. The CLI requests a
 * skill by id, and Hermes loads the body. The manifest is generated by a build
 * script, never hand-maintained, and the server validates it against the files
 * on disk at boot — a developer who edits a skill without rebuilding must not
 * ship a lying manifest.
 */

export const ManifestEntry = z.object({
  id: z.string(),
  displayName: z.string(),
  version: z.string(),
  description: z.string(),
  /** Trigger phrases that help the reasoning CLI route to this skill. */
  triggers: z.array(z.string()),
  service: z.string(),
  dependsOn: z.array(z.string()),
  /** Path to the skill file, relative to the skills root. */
  path: z.string(),
  /** File modification time in milliseconds — half of the staleness check. */
  mtimeMs: z.number(),
  /** File size in bytes — the other half of the staleness check. */
  size: z.number(),
});

export const SkillManifest = z.object({
  builtAt: z.string(),
  entries: z.array(ManifestEntry),
});

export type ManifestEntry = z.infer<typeof ManifestEntry>;
export type SkillManifest = z.infer<typeof SkillManifest>;

/** A file's identity on disk, for the staleness check. */
export interface FileStamp {
  path: string;
  mtimeMs: number;
  size: number;
}

/**
 * True when the manifest no longer matches the files on disk — a different set
 * of files, or any file's mtime or size changed since the manifest was built.
 */
export function isManifestStale(manifest: SkillManifest, files: readonly FileStamp[]): boolean {
  if (manifest.entries.length !== files.length) return true;

  const byPath = new Map(files.map((file) => [file.path, file]));
  for (const entry of manifest.entries) {
    const file = byPath.get(entry.path);
    if (file === undefined) return true;
    if (file.mtimeMs !== entry.mtimeMs || file.size !== entry.size) return true;
  }
  return false;
}

/** Renders the manifest as the compact index block for the prompt — each line
 *  carries the description and the trigger phrases, so the reasoning CLI has
 *  enough signal to request the right skill. */
export function renderManifestIndex(manifest: SkillManifest): string {
  if (manifest.entries.length === 0) return 'No skills are available.';
  const lines = ['Available skills — request the ones relevant to the task by id:'];
  const sorted = [...manifest.entries].sort((a, b) => a.id.localeCompare(b.id));
  for (const entry of sorted) {
    lines.push(`  - ${entry.id} (${entry.service}): ${entry.description}`);
    if (entry.triggers.length > 0) {
      lines.push(`      triggers: ${entry.triggers.join('; ')}`);
    }
  }
  return lines.join('\n');
}
